spring:
  application:
    name: gateway-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: MGdEZ4LVMNjlK0MEworLflUzTzEQcuzQ
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/gateway-lab

  cloud:
    gateway:
      routes:
        - id : ordinary-service-route
          uri : ${ORDINARY_SERVICE_URI:http://localhost:8081}
          predicates:
#            - Query=any
#            - Method=GET,POST
#            - Header=X-Request-Id, \d+
            - Path=/greetings/**
          filters:
#            - RedirectTo=302, https://spring.io
            - TokenRelay=
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-by,Eduardo Gateway Service
            - AddRequestHeadersIfNotPresent=X-Request-service-id:ordinary
            - name: UserAgent
              args:
                shouldRedirect : true
                postmanUrl : ${ORDINARY_SERVICE_URI:http://localhost:8081}/api/greetings/hello-postman
                browserUrl : ${ORDINARY_SERVICE_URI:http://localhost:8081}/api/greetings/hello-browser

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway